# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d15d6865d5bfcc87df1b8342866c1f0fca9a20d2bffbcf3bf30f7af53b40bd1f64b48c0582d5d3688f5e84659b34bd7e9928ce36263988ffd2ea2d13a25d4a94

test:
  secret_key_base: 01ed0e7020408724a8c381e08afef094690aa77f16f9ad40cd16b7c6cc8ee0ae5d45689cd1cc51b1064b13a6bd255187e4ade4dfde2df1948af1888877df6d15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
